config {
  type: "incremental",
  uniqueKey: ["person_id"],
  schema: "customer_onboarding",
  bigquery: {
    partitionBy: "DATE(update_time)"
  }
}

SELECT DISTINCT * EXCEPT(row_number, _airbyte_extracted_at)
FROM (
SELECT *,
    ROW_NUMBER() OVER (PARTITION BY person_id ORDER BY _airbyte_extracted_at DESC) AS row_number
FROM ${ref('raw_deal_person')}
) t
WHERE t.row_number = 1
  AND person_id IN (SELECT DISTINCT person_id FROM ${ref('deal')})