config {
  type: "incremental",
  uniqueKey: ["org_id"],
  schema: "sale",
  bigquery: {
    partitionBy: "DATE(update_time)"
  }
}

WITH
    raw_organization AS (SELECT DISTINCT * FROM ${ref('raw_organization')})

SELECT DISTINCT * EXCEPT(row_number)
FROM (
SELECT *,
    ROW_NUMBER() OVER (PARTITION BY org_id ORDER BY update_time DESC) AS row_number
FROM raw_organization
) t
WHERE t.row_number = 1