config {
  type: "table",
  uniqueKey: ['ad_id'],
  schema: "your_schema",
  name: "ads",
  dependencies: ["assert_ads"]
}

SELECT DISTINCT * EXCEPT(row_number)
FROM (
  SELECT distinct *,
      ROW_NUMBER() OVER (PARTITION BY ad_id ORDER BY updated_time DESC) AS row_number
  FROM ${ref('view_ads')}
) t
WHERE t.row_number = 1
  AND (SELECT count(*) FROM ${ref('assert_ads')} WHERE invalid_count > 0) = 0