config {
  type: "table",
  uniqueKey: ['adset_id'],
  schema: "your_schema",
  name: "adsets",
  dependencies: ["assert_adsets"]
}

SELECT DISTINCT * EXCEPT(row_number)
FROM (
  SELECT distinct *,
      ROW_NUMBER() OVER (PARTITION BY adset_id ORDER BY updated_time DESC) AS row_number
  FROM ${ref('view_adsets')}
) t
WHERE t.row_number = 1 
  AND (SELECT count(*) FROM ${ref('assert_adsets')} WHERE invalid_count > 0) = 0
